"""RBAC permission and role constants."""

PERMISSIONS = [
    "admin:*",
    "auth:users:read",
    "auth:users:write",
    "auth:roles:read",
    "auth:roles:write",
    "inventory:materials:read",
    "inventory:materials:write",
    "inventory:warehouses:read",
    "inventory:warehouses:write",
    "inventory:stock:read",
    "inventory:stock:write",
    "orders:rfq:read",
    "orders:rfq:write",
    "orders:quotes:read",
    "orders:quotes:write",
    "orders:quotes:approve",
    "orders:sales:read",
    "orders:sales:write",
    "orders:invoices:read",
    "orders:invoices:write",
    "production:boms:read",
    "production:boms:write",
    "production:work-orders:read",
    "production:work-orders:write",
    "production:cutlists:read",
    "production:cutlists:write",
    "ai:use",
    "notifications:read",
    "notifications:write",
]

ROLES = ["admin", "supplier", "factory", "customer", "viewer"]

# Role -> list of permission codes
DEFAULT_ROLE_PERMISSIONS = {
    "admin": ["admin:*"],
    "supplier": [
        "inventory:materials:read",
        "inventory:materials:write",
        "inventory:warehouses:read",
        "inventory:warehouses:write",
        "inventory:stock:read",
        "inventory:stock:write",
        "orders:rfq:read",
        "orders:rfq:write",
        "orders:quotes:read",
        "orders:quotes:write",
        "orders:sales:read",
        "orders:sales:write",
        "orders:invoices:read",
        "orders:invoices:write",
        "production:boms:read",
        "production:boms:write",
        "production:work-orders:read",
        "production:work-orders:write",
        "production:cutlists:read",
        "production:cutlists:write",
        "ai:use",
        "notifications:read",
        "notifications:write",
    ],
    "factory": [
        "inventory:materials:read",
        "inventory:warehouses:read",
        "inventory:stock:read",
        "inventory:stock:write",
        "orders:rfq:read",
        "orders:quotes:read",
        "orders:quotes:approve",
        "orders:sales:read",
        "orders:invoices:read",
        "production:boms:read",
        "production:boms:write",
        "production:work-orders:read",
        "production:work-orders:write",
        "production:cutlists:read",
        "production:cutlists:write",
        "ai:use",
        "notifications:read",
        "notifications:write",
    ],
    "customer": [
        "inventory:materials:read",
        "orders:rfq:read",
        "orders:rfq:write",
        "orders:quotes:read",
        "orders:sales:read",
        "orders:invoices:read",
        "notifications:read",
        "notifications:write",
    ],
    "viewer": [
        "inventory:materials:read",
        "inventory:warehouses:read",
        "inventory:stock:read",
        "orders:rfq:read",
        "orders:quotes:read",
        "orders:sales:read",
        "orders:invoices:read",
        "production:boms:read",
        "production:work-orders:read",
        "notifications:read",
    ],
}
